# 触发 petpet 的指令
command: pet
# 使用 戳一戳 的触发概率
probability: 30
# 是否使用抗锯齿
antialias: true
# 禁用列表
disabled: []
# keyCommand前缀
commandHead: ''
# 是否响应机器人发出的戳一戳
respondSelfNudge: false
# 是否使用响应回复
respondReply: true
# 消息缓存池容量
cachePoolSize: 10000
# keyList响应格式
keyListFormat: FORWARD
# 禁用策略
disablePolicy: FULL
# 禁用群聊列表
disabledGroups: []
# 是否使用模糊匹配用户名
fuzzy: false
# 是否使用严格匹配模式
strictCommand: true
# 是否使用消息事件同步锁
synchronized: false
# GIF编码器
gifEncoder: ANIMATED_LIB
# GIF缩放阈值/尺寸
gifMaxSize: 
  - 200
  - 200
  - 32
# GIF质量, 仅适用于ANIMATED_LIB编码器
gifQuality: 100
# 是否使用headless模式
headless: true
# 图片合成线程池容量, 填入0为CPU线程数+1 (默认值)
threadPoolSize: 0
# 是否自动从仓库同步PetData
autoUpdate: true
# 用于自动更新的仓库地址
repositoryUrl: 'https://raw.githubusercontent.com/Dituon/petpet/main'
# 是否启用开发模式 (支持热重载)
devMode: false
# 触发图片生成后的用户冷却时长, 填入-1则禁用, 单位为秒
coolDown: 10
# 触发图片生成后的群聊冷却时长
groupCoolDown: -1
# 触发冷却后的回复消息, '[nudge]'为戳一戳
inCoolDownMessage: 技能冷却中...